

export const START_LOADING_TRANDING_GAMES = 'START_LOADING_TRANDING_GAMES'
export const FAILED_TRANDING_GAMES = 'FAILED_TRANDING_GAMES'
export const RECEIVED_TRANDING_GAMES = 'RECEIVED_TRANDING_GAMES'
